/*
 * Replicate HTTP API
 *
 * A web service for running Replicate models
 *
 * The version of the OpenAPI document: 1.0.0-a1
 * Contact: team@replicate.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = dotnetReplicate.Client.OpenAPIDateConverter;

namespace dotnetReplicate.Model
{
    /// <summary>
    /// DeploymentsGet200ResponseCurrentReleaseConfigurationScaling
    /// </summary>
    [DataContract(Name = "deployments_get_200_response_current_release_configuration_scaling")]
    public partial class Scaling : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Scaling" /> class.
        /// </summary>
        /// <param name="maxInstances">The maximum number of instances for scaling..</param>
        /// <param name="minInstances">The minimum number of instances for scaling..</param>
        public Scaling(int maxInstances = default(int), int minInstances = default(int))
        {
            this.MaxInstances = maxInstances;
            this.MinInstances = minInstances;
        }

        /// <summary>
        /// The maximum number of instances for scaling.
        /// </summary>
        /// <value>The maximum number of instances for scaling.</value>
        [DataMember(Name = "max_instances", EmitDefaultValue = false)]
        public int MaxInstances { get; set; }

        /// <summary>
        /// The minimum number of instances for scaling.
        /// </summary>
        /// <value>The minimum number of instances for scaling.</value>
        [DataMember(Name = "min_instances", EmitDefaultValue = false)]
        public int MinInstances { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DeploymentsGet200ResponseCurrentReleaseConfigurationScaling {\n");
            sb.Append("  MaxInstances: ").Append(MaxInstances).Append("\n");
            sb.Append("  MinInstances: ").Append(MinInstances).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
